[package]
name = "rad"
version = "0.1.4"
authors = ["Wafelack <wafelack@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "5.0"
libc = "0.2.88"
toml = "0.5.8"
pam = "0.7.0"
