.TH PORK 1 2021-06-13 "General Commands"

.SH NAME
pork \- Permission OverRide Kontroller

.SH SYNOPSIS
.B pork
.IR COMMAND
.IR ARGS...

.SH DESCRIPTION
\fBpork\fR allows you to override permissions and run a command as root.

.SH CONFIGURATION
\fBpork\fR is configured by editing the \fIsrc/config.rs\fR file and compiling the source code.

.SH EXAMPLE
pork mount /dev/sda1 /mnt

.SH AUTHORS
Written by Wafelack.

.SH COPYRIGHT
Copyright (C) 2021 Miniutils.
.br
License GPLv3: GNU General Public License version 3.0 or later.
.br
This is free software: your are free to change and redistribute it.
.br
There is NO WARRANTY, to extent permitted by law.

.SH REPORTING BUGS
Please report any bug to the pork repository issues page
.br
    <https://github.com/miniutils/pork/issues/new>
